name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint:fix

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build
        env:
          CI: false # This prevents treating warnings as errors


    # Note: Deployment steps will be added later when we set up Firebase hosting
    # - name: Deploy to Firebase
    #   uses: FirebaseExtended/action-hosting-deploy@v0
    #   with:
    #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
    #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
    #     channelId: live
    #     projectId: your-project-id
